config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'illusts#index'
  
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'show_all_illusts'
      get 'show_all_novels'
      get 'show_all_products'
    end
  end

  resources :illusts do
    resources :illust_comments, only: :create
    resources :illust_likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :novels do
    resources :novel_comments, only: :create
    resources :novel_likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  
  resources :products do
    resources :product_comments, only: :create
    resources :product_likes, only: [:create, :destroy]

    resources :orders, only: [:index, :create]
    
    collection do
      get 'search'
    end
  end

  resources :carts, only: [:create, :destroy]
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  # validation
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  VALID_NAME_REGEX = /\A[ぁ-んァ-ン一-龥々ー－]+\z/.freeze
  VALID_RUBY_REGEX = /\A[ァ-ヶー－]+\z/.freeze
  
  validates :password,        format: { with: VALID_PASSWORD_REGEX, if: :password_required? }
  with_options presence: true do
    validates :nickname, uniqueness: true
    validates :last_name,       format: { with: VALID_NAME_REGEX }
    validates :first_name,      format: { with: VALID_NAME_REGEX }
    validates :last_name_ruby,  format: { with: VALID_RUBY_REGEX }
    validates :first_name_ruby, format: { with: VALID_RUBY_REGEX }
    validates :birth
    validates :prefecture
    validates :municipality
    validates :address
  end
  validate :age
  
  # Association
  has_many :illusts, dependent: :destroy
  has_many :illust_comments, dependent: :destroy
  has_many :illust_likes, dependent: :destroy

  has_many :novels, dependent: :destroy
  has_many :novel_comments, dependent: :destroy
  has_many :novel_likes, dependent: :destroy

  has_many :products, dependent: :destroy
  has_many :product_comments, dependent: :destroy
  has_many :product_likes, dependent: :destroy
  
  has_many :orders, dependent: :destroy
  
  has_one  :cart


  private
  # 誕生日から年齢を計算しバリデータ
  def age
    year = birth.year.to_s
    month = ("%02d" % birth.month).to_s
    day = ("%02d" % birth.day).to_s
    date_birth = (year + month + day).to_i
    ages = ((Date.today.strftime('%Y%m%d').to_i - date_birth) / 10000).floor
    if ages.present? && ages < 18
      errors.add(:age, "must be 18 or older")
    end
  end
  # 登録情報変更時にパスワード除外
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

   def update_resource(resource, params)
    resource.update_without_current_password(params) #独自のメソッド。解説は下記にて。
   end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :show_all_illusts, :show_all_novels, :show_all_products, :edit, :update]

  def show
    user = User.find(params[:id])
    @user = user.nickname
    @illust = user.illusts.limit(5).order(created_at: 'desc')
    @novel = user.novels.limit(5).order(created_at: 'desc')
    @product = user.products.limit(5).order(created_at: 'desc')
  end

  def show_all_illusts
    user = User.find(params[:id])
    @user = user.nickname
    @illust = user.illusts.page(params[:page]).order(created_at: 'desc')
  end

  def show_all_novels
    user = User.find(params[:id])
    @user = user.nickname
    @novel = user.novels.page(params[:page]).order(created_at: 'desc')
  end

  def show_all_products
    user = User.find(params[:id])
    @user = user.nickname
    @product = user.products.page(params[:page]).order(created_at: 'desc')
  end

  def edit
  end


  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :nickname, :prefecture, :municipality, :address, :building)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class='confirmation_wrapper'>
  <div class = 'confirmation_form'>
    <%= form_with model: current_user, class: 'registration_main', local: true do |f| %>
      <%= render "shared/error_messages", model: current_user %>

      <div class = "confirmation_group">
        <div class="confirmation_email">
          <%= f.label :email, "メールアドレス" %><br />
          <%= f.email_field :email, placeholder: "必須", autofocus: true, autocomplete: "email" %>
        </div>
        
        <div class="confirmation_nickname">
          <%= f.label :nickname, "ニックネーム" %><br />
          <%= f.text_field :nickname, placeholder: "必須　重複不可", id:"nickname" %>
        </div>
      </div>
      <div class = "confirmation_group">
        <div class="confirmation_prefecture">
          <%= f.label :prefecture, "都道府県" %><br />
          <%= f.text_field :prefecture, placeholder: "必須", id:"prefecture" %>
        </div>

        <div class="confirmation_municipality">
          <%= f.label :municipality, "市区町村" %><br />
          <%= f.text_field :municipality, placeholder: "必須", id:"municipality" %>
        </div>

        <div class="confirmation_address">
          <%= f.label :address, "番地" %><br />
          <%= f.text_field :address, placeholder: "必須", id:"address" %>
        </div>

        <div class="confirmation_building">
          <%= f.label :building, "建物名" %><br />
          <%= f.text_field :building, id:"building" %>
        </div>

        <div class="actions">
          <%= f.submit "変更を適用", class: "confirmation-submit" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if current_user.nickname == @user %>
  <div class = "wrapper_center">
    <div class = "user_edit_btn"><%= link_to "登録情報の変更", edit_user_path %></div>
  </div>
<% end %>

<h1 class = "users_show_title" ><%= "#{@user}さんのイラスト" %></h1>
<ul class = "new_posts">
  <% @illust.each do |illust| %>
    <li class = "main_content">
      <%= link_to illust_path(illust.id) do %>
        <%= image_tag illust.images[0], class: "thumbnail" %><br>
      <% end %>
    </li>
  <% end %>
</ul>
<div class = "to_show_all"><%= link_to '全てのイラストを見る', show_all_illusts_user_path(current_user.id), name: 'illust' %></div>

<h1 class = "users_show_title"><%= "#{@user}さんの小説" %></h1>
<ul class = "new_posts">
  <% @novel.each do |novel| %>
    <li class = "main_novel">
      <%= link_to image_tag("book_title.png"),novel_path(novel.id), class: "novel_image" %>
      <%= link_to novel.title, novel_path(novel.id), class: "new_novel_title" %>
    </li>
  <% end %>
</ul>
<div class = "to_show_all"><%= link_to '全ての小説を見る', show_all_novels_user_path(current_user.id) %></div>

<h1 class = "users_show_title"><%= "#{@user}さんの商品" %></h1>
<ul class = "new_posts">
  <% @product.each do |product| %>
    <li class = "main_content">
      <%= link_to product_path(product.id) do %>
        <%= image_tag product.images[0], class: "thumbnail" %><br>
      <% end %>
    </li>
  <% end %>
</ul>
<div class = "to_show_all"><%= link_to '全ての商品を見る', show_all_products_user_path(current_user.id) %></div>

app/views/users/show_all_illusts.html.erb
<h1 class = "users_show_title"><%= "#{@user}さんのイラスト" %></h1>
<ul class = "new_posts">
  <% @illust.each do |illust| %>
    <li class = main_content>
      <%= link_to illust_path(illust.id) do %>
        <%= image_tag illust.images[0], class: "thumbnail" %><br>
      <% end %>
    </li>
  <% end %>
</ul>
<div class='pagination'><%= paginate(@illust) %></div>

app/views/users/show_all_novels.html.erb
<h1 class = "users_show_title"><%= "#{@user}さんの小説" %></h1>
<ul class = "new_posts">
  <% @novel.each do |novel| %>
    <li class = "main_novel">
      <%= link_to image_tag("book_title.png"),novel_path(novel.id), class: "novel_image" %>
      <%= link_to novel.title, novel_path(novel.id), class: "new_novel_title" %>
    </li>
  <% end %>
</ul>
<div class='pagination'><%= paginate(@novel) %></div>

app/views/users/show_all_products.html.erb
<h1 class = "users_show_title"><%= "#{@user}さんの商品" %></h1>
<ul class = "new_posts">
  <% @product.each do |product| %>
    <li class = main_content>
      <%= link_to product_path(product.id) do %>
        <%= image_tag product.images[0], class: "thumbnail" %><br>
      <% end %>
    </li>
  <% end %>
</ul>
<div class='pagination'><%= paginate(@product) %></div>