config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'illusts#index'
  
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'show_all_illusts'
      get 'show_all_novels'
      get 'show_all_products'
    end
  end

  resources :illusts do
    resources :illust_comments, only: :create
    resources :illust_likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :novels do
    resources :novel_comments, only: :create
    resources :novel_likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  
  resources :products do
    resources :product_comments, only: :create
    resources :product_likes, only: [:create, :destroy]

    resources :orders, only: [:index, :create]
    
    collection do
      get 'search'
    end
  end

  resources :carts, only: [:create, :destroy]
  
end

app/models/novel.rb
class Novel < ApplicationRecord

  # Validation

  with_options presence: true do
    validates :title
    validates :content
  end

  # Association
  has_many :novel_comments, dependent: :destroy
  has_many :novel_likes
  has_many :novel_tag_relations
  has_many :novel_tags, through: :novel_tag_relations
  has_many_attached :images
  has_rich_text :content
  belongs_to :user

  def liked?(user)
    novel_likes.where(user_id: user.id).exists?
  end
  
  def self.search(search)
    if search != ""
      @novel = Novel.where('title LIKE(?)', "%#{search}%")
    else
      @novel = Novel.all
    end
  end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :show, :edit, :update, :destroy, :search]
  before_action :set_find, only: [:show, :edit, :update, :destroy]

  def index
    @novel = Novel.includes(:user).limit(10).order("created_at DESC")
    @ranking = Novel.find(NovelLike.group(:novel_id).limit(10).order('count(novel_id) desc').pluck(:novel_id))
  end
  
  def new
    @novel = Novel.new
  end

  def create
    @novel = Novel.new(novel_params)
    if @novel.save
      redirect_to novel_path(@novel.id)
    else
      render :new
    end
  end

  def show
    @comment = NovelComment.new
    @comments = @novel.novel_comments.includes(:user)
    @like_count = NovelLike.where(novel_id: @novel.id).count
  end

  def edit
    if user_signed_in? && @novel.user_id != current_user.id
      redirect_to root_path
    end
  end

  def update
    @novel.update(novel_params)
    if @novel.save
      redirect_to novel_path
    else
      render :edit
    end
  end

  def destroy
    @novel.destroy if user_signed_in? && current_user.id == @novel.user.id
    redirect_to root_path
  end

  def search
    @novel = Novel.search(params[:keyword]).page(params[:page]).order(created_at: 'desc')
  end

  private
  def novel_params
    params.require(:novel).permit(:title, :application, :content).merge(user_id: current_user.id)
  end

  def set_find
    @novel = Novel.find(params[:id])
  end

end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/novels/edit.html.erb
<div class="form_wrapper">
  <%= form_with model:@novel, id: 'new_post',local: true do |f| %>
    <%# top %>
    <div class = "form_top">
      <div class="title_form">小説の情報を入力してください</div>
    </div>
    <%# title %>
    <div>
      <div class = "messages">
        タイトル
        <span class="indispensable">　必須</span>
      </div>
        <div class = "message_upload">
          <%= f.text_area :title, class:"post_text", id:"post_title", placeholder:"必須 20文字まで", maxlength:"20" %>
        </div>
      </div>
    </div>
    <%# app %>
    <div>
      <div class = "messages">
        使用したアプリケーション
        <span class="indispensable">　必須</span>
      </div>
        <div class = "message_upload">
          <%= f.text_area :application, class:"post_text", id:"post_title", placeholder:"必須 20文字まで", maxlength:"20" %>
        </div>
      </div>
    </div>
    <%# text %>
    <div class="items-detail">
      <div class = "messages">
        テキストフォームを使用して小説を作成してください
        <span class="indispensable">　必須</span>
      </div>
      <div class = "message_rich">
        <%= f.rich_text_area :content %>
      </div>
    </div>

    <div class = "message_upload">
      <div class="submit-btn">
        <%= f.submit '送信' %>
      </div>
    </div>
  <% end %>
</div>

app/views/novels/index.html.erb
<div class = "main_wrapper">
    <div class = "main_top">
      <div class = "advertisement">
          広告を設置
      </div>
      <div class = "search_form">
        <div>
          <%= form_with(url: search_novels_path, local: true, method: :get, class: "search_forms") do |f| %>
            <%= f.text_field :keyword, placeholder: "小説を検索する", class: "search_input" %>
            <%= f.submit "検索", class: "search_btn" %>
          <% end %>
        </div>
      </div>
      <div class = "select_ber">
        <div class = "select_btn">
          <%= link_to "イラスト", illusts_path, class: :illust_btn %>
          <%= link_to "小説",  novels_path, class: :novel_btn %>
          <%= link_to "商品", products_path, class: :item_btn %>
        </div>
      </div>
    </div>
    <div class = "main_center">
      <div class = "main_contents">
        <div class = "new_title">
        <a>New Novels!</a>
        </div>
        <ul class = "new_posts">
            <% @novel.each do |novel| %>
              <li class = "main_novel">
                <%= link_to image_tag("book_title.png"),novel_path(novel.id), class: "novel_image" %>
                <%= link_to novel.title, novel_path(novel.id), class: "new_novel_title" %>
                <%= link_to "❤︎#{novel.novel_likes.count}", novel_path(novel.id), class: "novel_likes"%>
              </li>
            <% end %>
        </ul>
        <div class = "ranking_title">
        ranking
        </div>
        <ul class = "ranking_posts">
          <% @ranking.each.with_index(1) do |rank| %>
            <li class = main_novel>
              <%= link_to image_tag("book_title.png"),novel_path(rank.id), class: "novel_image" %>
              <%= link_to rank.title, novel_path(rank.id), class: "new_novel_title" %>
              <%= link_to "❤︎#{rank.novel_likes.count}", novel_path(rank.id), class: "novel_likes"%>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
</div>

app/views/novels/new.html.erb
<div class="form_wrapper">
  <%= form_with model:@novel, id: 'new_post',local: true do |f| %>
    <%# top %>
    <div class = "form_top">
      <div class="title_form">小説の情報を入力してください</div>
    </div>
    <%= render 'shared/error_messages', model: @novel %>
    <%# title %>
    <div>
      <div class = "messages">
        タイトル
        <span class="indispensable">　必須</span>
      </div>
        <div class = "message_upload">
          <%= f.text_area :title, class:"post_text", id:"post_title", placeholder:"必須 20文字まで", maxlength:"20" %>
        </div>
      </div>
    </div>
    <%# app %>
    <div>
      <div class = "messages">
        使用したアプリケーション
        <span class="indispensable">　任意</span>
      </div>
        <div class = "message_upload">
          <%= f.text_area :application, class:"post_text", id:"post_title", placeholder:"必須 20文字まで", maxlength:"20" %>
        </div>
      </div>
    </div>
    <%# text %>
    <div class="items-detail">
      <div class = "messages">
        小説を作成してください
        <span class="indispensable">　必須</span>
      </div>
      <div class = "message_rich">
        <%= f.rich_text_area :content %>
      </div>
    </div>

    <div class = "message_upload">
      <div class="submit-btn">
        <%= f.submit '送信' %>
      </div>
    </div>
  <% end %>
</div>

app/views/novels/search.html.erb
<div class = "main_wrapper">

    <%# 画面上部 %>
    <div class = "main_top">
      <div class = "advertisement">
          広告を設置
      </div>
      <div class = "search_form">
        <div>
          <%= form_with(url: search_novels_path, local: true, method: :get, class: "search_forms") do |f| %>
            <%= f.text_field :keyword, placeholder: "小説を検索する", class: "search_input" %>
            <%= f.submit "検索", class: "search_btn" %>
          <% end %>
        </div>
      </div>
      <% if params[:keyword].present? %>
        <div class = "keyword"><%= "#{params[:keyword]}の検索結果" %></div>
      <%end%>
      <div class = "select_ber">
        <div class = "select_btn">
          <%= link_to "イラスト", search_illusts_path(keyword: params[:keyword]),method: :get, class: :illust_btn %>
          <%= link_to "小説",  search_novels_path(keyword: params[:keyword]),method: :get, class: :novel_btn %>
          <%= link_to "商品", search_products_path(keyword: params[:keyword]),method: :get, class: :item_btn %>
        </div>
      </div>
    </div>
    <%# メインコンテンツ %>
    <div class = main_center>
      <div class = "main_contents" >
        <ul class = "new_posts">
          <% @novel.each do |novel| %>
            <li class = "main_novel">
               <%= link_to image_tag("book_title.png"),novel_path(novel.id), class: "novel_image" %>
               <%= link_to novel.title, novel_path(novel.id), class: "new_novel_title" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <%# ページネーションバー %>
    <div class='pagination'><%= paginate(@novel) %></div>
</div>

  
</div>

app/views/novels/show.html.erb
<div class="posted_content">

  <%# ユーザーメニューを表示 %>
  <div class = "contributor_menu">
    <% if user_signed_in? && current_user.id == @novel.user_id %>
        <%= link_to "編集", edit_novel_path(@novel.id), method: :get, class: "edit_btn" %>
        <%= link_to "削除", novel_path(@novel.id), method: :delete, class:"destroy_btn" %>
    <% end %>
  </div>

  <%# いいねボタン %>
  <% if @novel.liked?(current_user) %>
    <%= link_to novel_novel_like_path(@novel.id), method: :delete do %>
      <span style= "color:red;">❤︎</span>
    <% end %>
    <div class = "m_bottom"><%= @like_count %></div>
  <% else %>
    <%= link_to novel_novel_likes_path(@novel.id), method: :post do %>
      <span>❤︎</span>
    <% end %>
    <div class = "m_bottom"><%= @like_count %></div>
  <% end %>

  <%# タイトルを表示 %>
  <div class = "posted_title">
    <%= @novel.title%><br>
  </div>
  <%# 小説を表示 %>
  <div class = "posted_rich">
    <%= @novel.content%>
  </div>
  <%# 使用したアプリがあれば表示 %>
  <% if @novel.application.present?%>
    <div>
    created by  <%= @novel.application%>
    </div>
  <% end %>

  <%# コメント投稿 %>
  <div class = "comment-wrapper">
    <div class="container">
      <%= form_with(model: [@novel, @comment], local: true) do |f| %>
        <%= f.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= f.submit "SEND" %>
      <% end %>
    </div>
    <%# コメント表示 %>
    <div class="comments">
        <h4 class = "comment-view" >コメント一覧</h4>
        <% @comments.each do |comments| %>
          <p>
            <strong class = "comment-nickname"><%= comments.user.nickname %></strong>
            <%= comments.text %>
          </p>
        <% end %>
    </div>
  </div>
</div>