config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'illusts#index'
  
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'show_all_illusts'
      get 'show_all_novels'
      get 'show_all_products'
    end
  end

  resources :illusts do
    resources :illust_comments, only: :create
    resources :illust_likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :novels do
    resources :novel_comments, only: :create
    resources :novel_likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  
  resources :products do
    resources :product_comments, only: :create
    resources :product_likes, only: [:create, :destroy]

    resources :orders, only: [:index, :create]
    
    collection do
      get 'search'
    end
  end

  resources :carts, only: [:create, :destroy]
  
end

app/models/product.rb
class Product < ApplicationRecord

  # Validation
  with_options presence: true do
    validates :images
    validates :file
    validates :title
    validates :description
    validates :application
    validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 100, less_than_or_equal_to: 99999 }
  end
  validate :file_content_type, if: :file_was_attached?
  validate :images_content_type, if: :images_was_attached?


  # Association
  has_many           :product_comments, dependent: :destroy
  has_many           :product_likes
  has_many           :product_tag_relations
  has_many           :product_tags, through: :product_tag_relations
  has_many_attached  :images

  has_one            :order
  has_one_attached   :file
  
  belongs_to         :user
  belongs_to         :cart

  def liked?(user)
    product_likes.where(user_id: user.id).exists?
  end

  private
  # ファイルの拡張子判定
  def file_content_type
    extension = 'application/zip'
    errors.add(:file, "の拡張子が間違っています") unless file.content_type.in?(extension)
  end

  def file_was_attached?
    self.file.attached?
  end

  # 画像の拡張子判定
  def images_content_type
    images.each do |image|
      extension = ['image/png', 'image/jpg', 'image/jpeg']
      errors.add(:images, "の拡張子が間違っています") unless image.content_type.in?(extension)
    end
  end

  def images_was_attached?
    self.images.attached?
  end

 


  # 検索結果の分岐
  def self.search(search)
    if search != ""
      @product = Product.where('title LIKE(?)', "%#{search}%")
    else
      @product = Product.all
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :show, :edit, :update, :destroy, :search]
  before_action :set_find, only: [:show, :edit, :update, :destroy]

  def index
    @product = Product.includes(:user).limit(10).order("created_at DESC")
    @ranking = Product.find(ProductLike.group(:product_id).limit(10).order('count(product_id) desc').pluck(:product_id))
  end
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product.id)
    else
      render :new
    end
  end

  def show
    products = @product.id
    user = current_user.id
    @order = Order.where(user_id: user).where(product_id: products)

    @comment = ProductComment.new
    @comments = @product.product_comments.includes(:user)

    @like_count = ProductLike.where(product_id: @product.id).count
  end

  def edit
    if user_signed_in? && @product.user_id != current_user.id
      redirect_to root_path
    end
  end

  def update
    @product.update(product_params)
    if @product.save
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy
    @product.destroy if user_signed_in? && current_user.id == @product.user.id
    redirect_to root_path
  end

  def search
    @product = Product.search(params[:keyword]).page(params[:page]).order(created_at: 'desc')
  end

  private
  def product_params
    params.require(:product).permit(:title, :price, :description, :application, :file, {images: []}).merge(user_id: current_user.id)
  end

  def set_find
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class="form_wrapper">
  <%= form_with model:@product, id: 'product_post',local: true do |f| %>
    <%# top %>
    <div class = "form_top">
      <div class="title_form">商品の情報を入力してください</div>
    </div>
    <%= render 'shared/error_messages', model: @product %>
    <%# image %>
    <div class = "previews" id="product_previews"></div>
    <div class="img_upload">
      <div class = "messages">
        サンプル
        <span class="indispensable">　任意</span>
      </div>
      <div class = image-area>
        <div class="click_upload">
          <%= f.file_field :images, accept: "image/*", name: 'product[images][]', data: {index: 0} %>
        </div>
      </div>
    </div>
    <%# title %>
    <div>
      <div class = "messages">
        タイトル
        <span class="indispensable">　必須</span>
      </div>
        <div class = "message_upload">
          <%= f.text_area :title, class:"post_text", id:"post_title", placeholder:"20文字まで", maxlength:"20" %>
        </div>
        <div class = "messages">
          商品の説明
          <span class="indispensable">　必須</span>
        </div>
        <div class = "message_upload">
          <%= f.text_area :description, class:"post_description", id:"post_desc", placeholder:"500文字まで" ,rows:"1" ,maxlength:"500" %>
        </div>
      </div>
    </div>
    <%# application %>
    <div class="items-detail">
      <div class = "messages">
        使用したアプリケーション
        <span class="indispensable">　必須</span>
      </div>
      <div class = "message_upload">
        <%= f.text_area :application, class:"post_application", id:"post_app", placeholder:"50文字まで未使用なら　未使用と記入" ,rows:"1" ,maxlength:"50" %>
      </div>
    </div>
    <%# price %>
    <div class="items-detail">
      <div class = "messages">
        価格　半角数字のみ
        <span class="indispensable">　必須</span>
      </div>
      <div class = "message_upload">
        <%= f.text_area :price, class:"post_prompt", id:"product_price", placeholder:"800" %>
        <div>
          <span>手数料 (10%)</span>
          <span>
            <span id='tax_price'></span>円
          </span>
        </div>
        <div>
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <div class = "message_upload">
      <div class="submit-btn">
        <%= f.submit '送信' %>
      </div>
    </div>
  <% end %>
</div>

app/views/products/index.html.erb
<div class = "main_wrapper">
    <div class = "main_top">
      <div class = "advertisement">
          広告を設置
      </div>
      <div class = "search_form">
        <div>
          <%= form_with(url: search_products_path, local: true, method: :get, class: "search_forms") do |f| %>
            <%= f.text_field :keyword, placeholder: "商品を検索する", class: "search_input" %>
            <%= f.submit "検索", class: "search_btn" %>
          <% end %>
        </div>
      </div>
      <div class = "select_ber">
        <div class = "select_btn">
          <%= link_to "イラスト", illusts_path, class: :illust_btn %>
          <%= link_to "小説",  novels_path, class: :novel_btn %>
          <%= link_to "商品", products_path, class: :item_btn %>
        </div>
      </div>
    </div>
    <div class = main_center>
      <div class = "main_contents">
        <div class = "new_title">
          <a>New Items!</a>
        </div>
        <ul class = "new_posts">
              <% @product.each do |product| %>
                <li class = main_content>
                  <%= link_to product_path(product.id) do %>
                    <%= image_tag product.images[0], class: "thumbnail" %><br>
                    <div class = "illust_likes"><%= "❤︎#{product.product_likes.count}"%></div>
                  <% end %>
                </li>
              <% end %>
        </ul>
        <div class = "ranking_title">
        ranking
        </div>
        <ul class = "ranking_posts">
          <% @ranking.each.with_index(1) do |rank| %>
            <li class = main_content>
              <%= link_to product_path(rank.id) do %>
                <%= image_tag rank.images[0], class: "thumbnail" %><br>
                <div class = "illust_likes"><%= "❤︎#{rank.product_likes.count}"%></div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
</div>

app/views/products/new.html.erb
<div class="form_wrapper">
  <%= form_with model:@product, id: 'product_post',local: true do |f| %>
    <%# top %>
    <div class = "form_top">
      <div class="title_form">商品の情報を入力してください</div>
    </div>
    <%= render 'shared/error_messages', model: @product %>
    <%# image %>
    <div class = "previews" id="product_previews"></div>
    <div class="img_upload">
      <div class = "messages">
        サンプル
        <span class="indispensable">　任意</span>
      </div>
      <div class = image-area>
        <div class="click_upload">
          <%= f.file_field :images, accept: "image/*", name: 'product[images][]', data: {index: 0} %>
        </div>
      </div>
    </div>
    <%# file %>
    <div class="items-detail">
      <div class = "messages">
        商品のZIPファイル
        <span class="indispensable">　必須</span>
      </div>
      <div class = "message_upload">
        <%= f.file_field :file, class:"post_zip", accept: "application/zip", id:"post_zip" %>
      </div>
    </div>
    <%# title %>
    <div>
      <div class = "messages">
        タイトル
        <span class="indispensable">　必須</span>
      </div>
        <div class = "message_upload">
          <%= f.text_area :title, class:"post_text", id:"post_title", placeholder:"20文字まで", maxlength:"20" %>
        </div>
        <div class = "messages">
          商品の説明
          <span class="indispensable">　必須</span>
        </div>
        <div class = "message_upload">
          <%= f.text_area :description, class:"post_description", id:"post_desc", placeholder:"500文字まで" ,rows:"1" ,maxlength:"500" %>
        </div>
      </div>
    </div>
    <%# application %>
    <div class="items-detail">
      <div class = "messages">
        使用したアプリケーション
        <span class="indispensable">　必須</span>
      </div>
      <div class = "message_upload">
        <%= f.text_area :application, class:"post_application", id:"post_app", placeholder:"50文字まで未使用なら　未使用と記入" ,rows:"1" ,maxlength:"50" %>
      </div>
    </div>
    <%# price %>
    <div class="items-detail">
      <div class = "messages">
        価格　半角数字のみ
        <span class="indispensable">　必須</span>
      </div>
      <div class = "message_upload">
        <%= f.text_area :price, class:"post_prompt", id:"product_price", placeholder:"800" %>
        <div>
          <span>手数料 (10%)</span>
          <span>
            <span id='tax_price'></span>円
          </span>
        </div>
        <div>
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <div class = "message_upload">
      <div class="submit-btn">
        <%= f.submit '送信' %>
      </div>
    </div>
  <% end %>
</div>

app/views/products/search.html.erb
<div class = "main_wrapper">

    <%# 画面上部 %>
    <div class = "main_top">
      <div class = "advertisement">
          広告を設置
      </div>
      <div class = "search_form">
        <div>
          <%= form_with(url: search_products_path, local: true, method: :get, class: "search_forms") do |f| %>
            <%= f.text_field :keyword, placeholder: "商品を検索する", class: "search_input" %>
            <%= f.submit "検索", class: "search_btn" %>
          <% end %>
        </div>
      </div>
      <% if params[:keyword].present? %>
        <div class = "keyword"><%= "#{params[:keyword]}の検索結果" %></div>
      <%end%>
      <div class = "select_ber">
        <div class = "select_btn">
          <%= link_to "イラスト", search_illusts_path(keyword: params[:keyword]),method: :get, class: :illust_btn %>
          <%= link_to "小説",  search_novels_path(keyword: params[:keyword]),method: :get, class: :novel_btn %>
          <%= link_to "商品", search_products_path(keyword: params[:keyword]),method: :get, class: :item_btn %>
        </div>
      </div>
    </div>
    <%# メインコンテンツ %>
    <div class = main_center>
      <div class = "main_contents" >
        <ul class = "new_posts">
          <% @product.each do |product| %>
            <li class = main_content>
              <%= link_to product_path(product.id) do %>
                <%= image_tag product.images[0], class: "thumbnail" %><br>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <%# ページネーションバー %>
    <div class='pagination'><%= paginate(@product) %></div>
</div>

  
</div>

app/views/products/show.html.erb
<div class="posted_content">

  <%# ユーザーメニューを表示 %>
  <div class = "contributor_menu">
    <% if user_signed_in? && current_user.id == @product.user_id %>
        <%= link_to "編集", edit_product_path(@product.id), method: :get, class: "edit_btn" %>
        <%= link_to "削除依頼", product_path(@product.id), method: :delete, class:"destroy_btn" %>
    <% end %>
  </div>
  <%# タイトルを表示 %>
  <div class = "posted_title">
    <%= @product.title %><br>
  </div>
  <%# サンプル画像を表示 %>
  <li class = "view_product">
    <% @product.images.each do |image| %>
      <div class="product_image">
        <%= image_tag image %>
      </div><br>
    <%end%>
  </li>

  <%# いいねボタン %>
  <% if @product.liked?(current_user) %>
    <%= link_to product_product_like_path(@product.id), method: :delete do %>
      <span style= "color:red;">❤︎</span>
    <% end %>
    <div class = "m_bottom"><%= @like_count %></div>
  <% else %>
    <%= link_to product_product_likes_path(@product.id), method: :post do %>
      <span>❤︎</span>
    <% end %>
    <div class = "m_bottom"><%= @like_count %></div>
  <% end %>

  <%# 未購入時には購入ボタン、購入者にはダウンロードボタンを表示 %>
  <% if @product.user_id != current_user.id %>
    <% if @order.present? %>
      <div class = "posted_order">
        <td><%= button_to 'download', @product.file, method: :get, class: 'btn btn_info' %></td>
      </div>
    <% else %>
      <div class='products_buy_btn'>
        <%= link_to "購入", product_orders_path(@product.id), class: "buy_btn" %>
      </div> 
    <% end %>
  <% end %>
  <%# 商品の価格を表示 %>
  <div class = "posted_price">
    <%= @product.price %>　円<br>
  </div>
  <%# 商品の説明 %>
  <div class = "posted_description">
    <%= @product.description%>
  </div>
  <%# 使用したアプリを表示 %>
  <div class = "posted_application">
    <%= @product.application%>
  </div>

  <%# 購入者にはコメント投稿フォームを表示 %>
  <div class = "comment-wrapper">
    <% if @order.present? %>
      <div class="container">
        <%= form_with(model: [@product, @comment], local: true) do |f| %>
          <div><%= f.text_area :text, placeholder: "コメントする", rows: "2" %></div>
          <div><%= f.submit "SEND" %></div>
        <% end %>
      </div>
    <% end %>
    <%# コメント表示 %>
    <div class="comments">
        <h4 class = "comment-view">コメント一覧</h4>
        <% @comments.each do |comments| %>
          <p>
            <strong class = "comment-nickname"><%= comments.user.nickname %></strong>
            <%= comments.text %>
          </p>
        <% end %>
    </div>
  </div>
</div>