config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'illusts#index'
  
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'show_all_illusts'
      get 'show_all_novels'
      get 'show_all_products'
    end
  end

  resources :illusts do
    resources :illust_comments, only: :create
    resources :illust_likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :novels do
    resources :novel_comments, only: :create
    resources :novel_likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  
  resources :products do
    resources :product_comments, only: :create
    resources :product_likes, only: [:create, :destroy]

    resources :orders, only: [:index, :create]
    
    collection do
      get 'search'
    end
  end

  resources :carts, only: [:create, :destroy]
  
end

app/models/illust.rb
class Illust < ApplicationRecord
  # Validation

  with_options presence: true do
    validates :images
    validates :title
    validates :description
    validates :application
  end
  validate :images_content_type, if: :images_was_attached?
  
  # Association

  has_many :illust_comments, dependent: :destroy
  has_many :illust_likes, dependent: :destroy
  has_many :illust_tag_relations
  has_many :illust_tags, through: :illust_tag_relations
  has_many_attached :images

  belongs_to :user


  def liked?(user)
    illust_likes.where(user_id: user.id).exists?
  end
  private

  # 画像の拡張子判定
  def images_content_type
    images.each do |image|
      extension = ['image/png', 'image/jpg', 'image/jpeg']
      errors.add(:images, "の拡張子が間違っています") unless image.content_type.in?(extension)
    end
  end

  def images_was_attached?
    self.images.attached?
  end

  # 検索結果の分岐
  def self.search(search)
    if search != ""
      @illust = Illust.where('title LIKE(?)', "%#{search}%")
    else
      @illust = Illust.all
    end
  end
end

app/controllers/illusts_controller.rb
class IllustsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :edit, :update, :destroy, :search]
  before_action :set_find, only: [:show, :edit, :update, :destroy]

  def index
    @illust = Illust.includes(:user).limit(10).order("created_at DESC")
    @ranking = Illust.find(IllustLike.group(:illust_id).limit(10).order('count(illust_id) desc').pluck(:illust_id))
  end
  
  def new
    @illust = Illust.new
  end

  def create
    @illust = Illust.new(illust_params)
    if @illust.save
      redirect_to illust_path(@illust.id)
    else
      render :new
    end
  end

  def show
    @comment = IllustComment.new
    @comments = @illust.illust_comments.includes(:user)
    @like_count = IllustLike.where(illust_id: @illust.id).count
  end

  def edit
    if user_signed_in? && @illust.user_id != current_user.id
      redirect_to root_path
    end
  end

  def update
    @illust.update(illust_params)
    if @illust.save
      redirect_to illust_path
    else
      render :edit
    end
  end

  def destroy
    @illust.destroy if user_signed_in? && current_user.id == @illust.user.id
    redirect_to root_path
  end

  def search
    @illust = Illust.search(params[:keyword]).page(params[:page]).order(created_at: 'desc')
  end


  
  private
  def illust_params
    params.require(:illust).permit(:title, :description, :application, :prompt, {images: []}).merge(user_id: current_user.id)
  end

  def set_find
    @illust = Illust.find(params[:id])
  end

end

app/helpers/illusts_helper.rb
module IllustsHelper
end

app/views/illusts/edit.html.erb
<div class="form_wrapper">
  <%= form_with model:@illust, id: 'new_post',local: true do |f| %>
    <%# top %>
    <div class = "form_top">
      <div class="title_form">イラストの変更情報を入力してください</div>
    </div>
    <%= render 'shared/error_messages', model: @illust %>
    <%# image %>
    <div class = "previews" id="previews"></div>
    <div class="img_upload">
      <div class = "messages">
        イラストファイル
      </div>
      <div class = image-area>
        <div class="click_upload">
          <%= f.file_field :images, accept: "image/*", name: 'illust[images][]', data: {index: 0} %>
        </div>
      </div>
    </div>
    <div class="items-explain">
        <div class="weight-bold-text">
    <%# title %>
    <div>
      <div class = "messages">
        タイトル
      </div>
        <div class = "message_upload">
          <%= f.text_area :title, class:"post_text", id:"post_title", placeholder:"必須 20文字まで", maxlength:"20" %>
        </div>
        <div class = "messages">
          イラストの説明
        </div>
        <div class = "message_upload">
          <%= f.text_area :description, class:"post_description", id:"post_desc", placeholder:"必須 500文字まで" ,rows:"1" ,maxlength:"500" %>
        </div>
      </div>
    </div>
    <%# application %>
    <div class="items-detail">
      <div class = "messages">
        使用したアプリケーション
      </div>
      <div class = "message_upload">
        <%= f.text_area :application, class:"post_application", id:"post_app", placeholder:"必須 50文字まで" ,rows:"1" ,maxlength:"50" %>
      </div>
    </div>
    <%# application %>
    <div class="items-detail">
      <div class = "messages">
        プロンプトなど
      </div>
      <div class = "message_upload">
        <%= f.text_area :prompt, class:"post_prompt", id:"post_prompt", placeholder:"任意 500文字まで" ,rows:"1" ,maxlength:"500" %>
      </div>
    </div>
    <div class = "message_upload">
      <div class="submit-btn">
        <%= f.submit '送信' %>
      </div>
    </div>
  <% end %>
</div>

app/views/illusts/index.html.erb
<%# ログイン %>
<div class = "main_wrapper">
  <% if user_signed_in? %>
    <div class = "main_top">
      <div class = "advertisement">
          広告を設置
      </div>
      <div class = "search_form">
        <div>
          <%= form_with(url: search_illusts_path, local: true, method: :get, class: "search_forms") do |f| %>
            <%= f.text_field :keyword, placeholder: "イラストを検索する", class: "search_input" %>
            <%= f.submit "検索", class: "search_btn" %>
          <% end %>
        </div>
      </div>
      <div class = "select_ber">
        <div class = "select_btn">
          <%= link_to "イラスト", illusts_path, class: :illust_btn %>
          <%= link_to "小説",  novels_path, class: :novel_btn %>
          <%= link_to "商品", products_path, class: :item_btn %>
        </div>
      </div>
    </div>
    <div class = main_center>
      <div class = "main_contents">
        <div class = "new_title">
          <a>New Illustrations!</a>
        </div>
        <ul class = "new_posts">
              <% @illust.each do |illust| %>
                <li class = main_content>
                  <%= link_to illust_path(illust.id) do %>
                    <%= image_tag illust.images[0], class: "thumbnail" %><br>
                    <div class = "illust_likes"><%= "❤︎#{illust.illust_likes.count}"%></div>
                  <% end %>
                </li>
              <% end %>
        </ul>
        <div class = "ranking_title">
        ranking
        </div>
        <ul class = "ranking_posts">
            <% @ranking.each.with_index(1) do |rank| %>
              <li class = main_content>
                <%= link_to illust_path(rank.id) do %>
                  <%= image_tag rank.images[0], class: "thumbnail" %><br>
                  <div class = "illust_likes"><%= "❤︎#{rank.illust_likes.count}"%></div>
                <% end %>
              </li>
            <% end %>
        </ul>
      </div>
    </div>
    <%# 未ログイン %>
    <% else %>
    <div class = "intro_wrapper">
      <div class = "intro_texts">
        <div class = "intro_text1", id = "introduce_text1">作成したAI作品を見てもらいたい！</div>
        <div class = "intro_text2", id = "introduce_text2">作成したAI作品を売りたい！</div>
        <div class = "intro_text3", id = "introduce_text3">AI作品をもっと見たい！</div>
        <div class = "intro_text4", id = "introduce_text4">それならラスろう！！</div>
      </div>
      <div class = "intro_logo", id = "introduce_logo">
        <%= image_tag "ailus_logo_big.png" %>
      </div>
    </div>
  <%# ログイン分岐終了 %>
  <% end %>
</div>

app/views/illusts/new.html.erb
<div class="form_wrapper">
  <%= form_with model:@illust, id: 'new_post',local: true do |f| %>
    <%# top %>
    <div class = "form_top">
      <div class="title_form">イラストの情報を入力してください</div>
    </div>
    <%= render 'shared/error_messages', model: @illust %>
    <%# image %>
    <div class = "previews" id="previews"></div>
    <div class="img_upload">
      <div class = "messages">
        イラストファイル
        <span class="indispensable">　必須</span>
      </div>
      <div class = image-area>
        <div class="click_upload">
          <%= f.file_field :images, accept: "image/*", name: 'illust[images][]', data: {index: 0} %>
        </div>
      </div>
    </div>
    <div class="items-explain">
        <div class="weight-bold-text">
    <%# title %>
    <div>
      <div class = "messages">
        タイトル
        <span class="indispensable">　必須</span>
      </div>
        <div class = "message_upload">
          <%= f.text_area :title, class:"post_text", id:"post_title", placeholder:"必須 20文字まで", maxlength:"20" %>
        </div>
        <div class = "messages">
          イラストの説明
          <span class="indispensable">　必須</span>
        </div>
        <div class = "message_upload">
          <%= f.text_area :description, class:"post_description", id:"post_desc", placeholder:"必須 500文字まで" ,rows:"1" ,maxlength:"500" %>
        </div>
      </div>
    </div>
    <%# application %>
    <div class="items-detail">
      <div class = "messages">
        使用したアプリケーション
        <span class="indispensable">　必須</span>
      </div>
      <div class = "message_upload">
        <%= f.text_area :application, class:"post_application", id:"post_app", placeholder:"必須 50文字まで" ,rows:"1" ,maxlength:"50" %>
      </div>
    </div>
    <%# application %>
    <div class="items-detail">
      <div class = "messages">
        プロンプトなど
        <span class="indispensable">　任意</span>
      </div>
      <div class = "message_upload">
        <%= f.text_area :prompt, class:"post_prompt", id:"post_prompt", placeholder:"任意 500文字まで" ,rows:"1" ,maxlength:"500" %>
      </div>
    </div>
    <div class = "message_upload">
      <div class="submit-btn">
        <%= f.submit '送信' %>
      </div>
    </div>
  <% end %>
</div>

app/views/illusts/search.html.erb
<div class = "main_wrapper">
    
    <%# 画面上部 %>
    <div class = "main_top">
      <div class = "advertisement">
          広告を設置
      </div>
      <div class = "search_form">
        <div>
          <%= form_with(url: search_illusts_path, local: true, method: :get, class: "search_forms") do |f| %>
            <%= f.text_field :keyword, placeholder: "イラストを検索する", class: "search_input" %>
            <%= f.submit "検索", class: "search_btn" %>
          <% end %>
        </div>
      </div>
      <% if params[:keyword].present? %>
        <div class = "keyword"><%= "#{params[:keyword]}の検索結果" %></div>
      <%end%>
      <div class = "select_ber">
        <div class = "select_btn">
          <%= link_to "イラスト", search_illusts_path(keyword: params[:keyword]),method: :get, class: :illust_btn %>
          <%= link_to "小説",  search_novels_path(keyword: params[:keyword]),method: :get, class: :novel_btn %>
          <%= link_to "商品", search_products_path(keyword: params[:keyword]),method: :get, class: :item_btn %>
        </div>
      </div>
    </div>

    <%# メインコンテンツ %>
    <div class = "main_center" >
      <div class = "main_contents" >
        <ul class = "new_posts">
              <% @illust.each do |illust| %>
                <li class = "main_content" >
                  <%= link_to illust_path(illust.id) do %>
                    <%= image_tag illust.images[0], class: "thumbnail" %><br>
                  <% end %>
                </li>
              <% end %>
        </ul>
      </div>
    </div>
    <%# ページネーションバー %>
    <div class='pagination'><%= paginate(@illust) %></div>
</div>

  
</div>

app/views/illusts/show.html.erb
<div class="posted_content">

  <%# ユーザーメニューを表示 %>
  <div class = "contributor_menu">
    <% if user_signed_in? && current_user.id == @illust.user_id %>
        <%= link_to "編集", edit_illust_path(@illust.id), method: :get, class: "edit_btn" %>
        <%= link_to "削除", illust_path(@illust.id), method: :delete, class:"destroy_btn" %>
    <% end %>
  </div>

  <%# 最初のイラストを表示 %>
  <%= image_tag @illust.images[0], class: "main_image" %><br>
  <%# イラストを表示 %>
  <% if @illust.images.length != 1 %>
  <details class="other-images">
    <summary class = "view_all">イラストを全て表示</summary>
    <div class = "view_content">
      <% @illust.images[1..-1].each do |image| %>
        <div class="other_image">
          <%= image_tag image %>
        </div><br>
      <%end%>
    </div>
  </details>
  <% end %>

  <%# いいねボタン %>
  <% if @illust.liked?(current_user) %>
    <%= link_to illust_illust_like_path(@illust.id), method: :delete do %>
      <span style= "color:red;">❤︎</span>
    <% end %>
    <div class = "m_bottom"><%= @like_count %></div>
  <% else %>
    <%= link_to illust_illust_likes_path(@illust.id), method: :post do %>
      <span>❤︎</span>
    <% end %>
    <div class = "m_bottom"><%= @like_count %></div>
  <% end %>

  <%# タイトルを表示 %>
  <div class = "posted_title">
    <%= @illust.title%><br>
  </div>
  <%# 説明を表示 %>
  <div class = "posted_description">
    <%= @illust.description%>
  </div>
  <%# 使用アプリを表示 %>
  <div class = "posted_application">
    <%= @illust.application%>
  </div>
  <%# プロンプトがあれば表示 %>
  <div class = "posted_prompt">
    <% if @illust.prompt.present? %>
      <%= @illust.prompt%>
    <% end %>
  </div>

  <%# コメント投稿 %>
  <div class="comment-wrapper">
    <div class="container">
      <%= form_with(model: [@illust, @comment], local: true) do |f| %>
        <%= f.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= f.submit "SEND" %>
      <% end %>
    </div>
    <%# コメント表示 %>
    <div class="comments">
        <h4 class = "comment-view" >コメント一覧</h4>
        <% @comments.each do |comments| %>
          <div class = "comment-content">
            <div class = "comment-nickname"><%= comments.user.nickname %></div>
            <div class = "comment-text"><%= comments.text %></div>
          </div>
        <% end %>
    </div>
  </div>
</div>